#!/bin/bash

[[ `which shyaml` ]] || ( echo 'Needs shyaml "pip install shyaml"' && exit 0)


echo Loading Juju status...
juju status > /tmp/juju.yml

echo
echo Kibana Default Dashboard:
echo - http://`cat /tmp/juju.yml | shyaml get-value services.kibana.units.kibana/0.public-address`
echo Kibana Web Dashboard:
echo - http://`cat /tmp/juju.yml | shyaml get-value services.kibana.units.kibana/0.public-address`/index.html#/dashboard/file/web.json
echo
echo Graphite Dashboard:
echo - http://`cat /tmp/juju.yml | shyaml get-value services.graphite.units.graphite/0.public-address`
echo CPU User time Graph:
echo - "http://`cat /tmp/juju.yml | shyaml get-value services.graphite.units.graphite/0.public-address`/graphlot/?from=-1hour&until=-0hour&target=stats.*.cpu.user"
echo
echo Sensu Dashboard:
echo - http://`cat /tmp/juju.yml | shyaml get-value services.sensu-server.units.sensu-server/0.public-address`:8080
echo - Username: admin
echo - Password: `juju get sensu-server | shyaml get-value settings.dashboard_password.value`/clients
echo
echo Juju GUI:
echo - http://`cat /tmp/juju.yml | shyaml get-value services.juju-gui.units.juju-gui/0.public-address`
echo - Username: admin
echo - Password: 'admin-secret' from your ~/.juju/environments.yaml
